---
version: "2.0"

services:
  devtools:
    image: docker link
    volumes:
      - "$HOME/.aws:/root/.aws"
      - "$HOME/.ssh/known_hosts:/root/.ssh/known_hosts"
      - ".:/app"
      - "$HOME/.kube:/root/.kube"
    working_dir: /app
    environment:
      AWS_PROFILE:
      AWS_DEFAULT_REGION: ap-southeast-2
      ARTIFACTORY_USER:
      ARTIFACTORY_PASSWORD:
